channels:
- conda-forge
- nodefaults
dependencies:
- make
- mypy
- myst-parser
- pip
- postgresql
- pre-commit
- psycopg
- psycopg2
- pydata-sphinx-theme
- pytest
- pytest-cov
- sphinx
- sphinxcontrib-apidoc
- sqlalchemy==1.4*
- sqlalchemy-utils
- sqlalchemy-stubs
- typer
- pip:
  - pytest-postgresql
  - types-PyYAML
